//! Core data types for Solstice trading platform.

use chrono::{DateTime, Duration, Utc};
use serde::{Deserialize, Serialize};
use solana_sdk::pubkey::Pubkey;
use std::collections::HashMap;
use uuid::Uuid;

/// Unique identifier for a position.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct PositionId(pub Uuid);

impl PositionId {
    /// Generate a new unique position ID.
    pub fn new() -> Self {
        PositionId(Uuid::new_v4())
    }
}

impl Default for PositionId {
    fn default() -> Self {
        Self::new()
    }
}

/// Token pair for trading (e.g., SOL/USDC).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct TokenPair {
    /// Base token mint address.
    pub base: Pubkey,
    /// Quote token mint address (usually USDC or SOL).
    pub quote: Pubkey,
}

impl TokenPair {
    /// Create a new token pair.
    pub fn new(base: Pubkey, quote: Pubkey) -> Self {
        TokenPair { base, quote }
    }
}

impl std::fmt::Display for TokenPair {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "{}/{}",
            &self.base.to_string()[0..8],
            &self.quote.to_string()[0..8]
        )
    }
}

/// Price of an asset in a quoted currency.
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
pub struct Price {
    /// Price value (can be negative for derivatives).
    pub value: f64,
    /// Token pair this price represents.
    pub pair: TokenPair,
    /// Timestamp when price was recorded.
    pub timestamp: DateTime<Utc>,
    /// Confidence score for this price (0.0 to 1.0).
    pub confidence: f64,
}

impl Price {
    /// Create a new price.
    pub fn new(value: f64, pair: TokenPair, confidence: f64) -> Self {
        Price {
            value,
            pair,
            timestamp: Utc::now(),
            confidence: confidence.clamp(0.0, 1.0),
        }
    }

    /// Check if price is valid (positive, finite, reasonable confidence).
    pub fn is_valid(&self) -> bool {
        self.value.is_finite() && self.value > 0.0 && self.confidence >= 0.0
    }

    /// Get price as basis points relative to another price.
    pub fn basis_points_vs(&self, other: &Price) -> f64 {
        ((self.value - other.value) / other.value) * 10000.0
    }
}

impl std::fmt::Display for Price {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{} ({})", self.value, self.pair)
    }
}

/// Order book for a market.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OrderBook {
    /// Market token pair.
    pub market: TokenPair,
    /// Bid orders: (price, quantity) sorted by price descending.
    pub bids: Vec<(f64, u64)>,
    /// Ask orders: (price, quantity) sorted by price ascending.
    pub asks: Vec<(f64, u64)>,
    /// Timestamp when orderbook was recorded.
    pub timestamp: DateTime<Utc>,
}

impl OrderBook {
    /// Create a new orderbook.
    pub fn new(market: TokenPair, bids: Vec<(f64, u64)>, asks: Vec<(f64, u64)>) -> Self {
        OrderBook {
            market,
            bids,
            asks,
            timestamp: Utc::now(),
        }
    }

    /// Get the spread (difference between best ask and best bid).
    pub fn spread(&self) -> Option<f64> {
        match (self.best_bid(), self.best_ask()) {
            (Some(bid), Some(ask)) => Some(ask - bid),
            _ => None,
        }
    }

    /// Get the mid price (average of best bid and best ask).
    pub fn mid_price(&self) -> Option<f64> {
        match (self.best_bid(), self.best_ask()) {
            (Some(bid), Some(ask)) => Some((bid + ask) / 2.0),
            _ => None,
        }
    }

    /// Get the best bid price.
    pub fn best_bid(&self) -> Option<f64> {
        self.bids.first().map(|(price, _)| *price)
    }

    /// Get the best ask price.
    pub fn best_ask(&self) -> Option<f64> {
        self.asks.first().map(|(price, _)| *price)
    }

    /// Check if orderbook is valid (non-empty, no crossing).
    pub fn is_valid(&self) -> bool {
        if self.bids.is_empty() || self.asks.is_empty() {
            return false;
        }

        // Check that best bid < best ask (no crossing)
        if let (Some(bid), Some(ask)) = (self.best_bid(), self.best_ask()) {
            bid < ask
        } else {
            false
        }
    }
}

/// A trading signal generated by a strategy.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Signal {
    /// Unique signal ID.
    pub id: String,
    /// Strategy that generated this signal.
    pub strategy: String,
    /// Signal type (buy, sell, close, rebalance).
    pub signal_type: SignalType,
    /// Confidence score (0.0 to 1.0).
    pub confidence: f64,
    /// Timestamp when signal was generated.
    pub timestamp: DateTime<Utc>,
    /// Optional suggested position size in quote currency.
    pub suggested_size: Option<u64>,
    /// Strategy-specific metadata.
    pub metadata: serde_json::Value,
}

/// Type of trading signal.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum SignalType {
    /// Buy (open long position).
    Buy { pair: TokenPair },
    /// Sell (close long or open short).
    Sell { pair: TokenPair },
    /// Close existing position.
    Close { position_id: PositionId },
    /// Rebalance portfolio.
    Rebalance { reason: String },
}

impl Signal {
    /// Create a new signal.
    pub fn new(strategy: String, signal_type: SignalType, confidence: f64) -> Self {
        Signal {
            id: format!("{}", Uuid::new_v4()),
            strategy,
            signal_type,
            confidence: confidence.clamp(0.0, 1.0),
            timestamp: Utc::now(),
            suggested_size: None,
            metadata: serde_json::json!({}),
        }
    }

    /// Check if signal is valid (confidence above threshold).
    pub fn is_valid(&self, min_confidence: f64) -> bool {
        self.confidence >= min_confidence
    }
}

/// An open trading position.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Position {
    /// Unique position ID.
    pub id: PositionId,
    /// Token pair traded.
    pub pair: TokenPair,
    /// Quantity (negative for short).
    pub quantity: i64,
    /// Entry price.
    pub entry_price: f64,
    /// Current market price.
    pub current_price: f64,
    /// Time position was opened.
    pub opened_at: DateTime<Utc>,
    /// Optional time position will be closed (for time-limited positions).
    pub close_at: Option<DateTime<Utc>>,
}

impl Position {
    /// Create a new position.
    pub fn new(pair: TokenPair, quantity: i64, entry_price: f64) -> Self {
        Position {
            id: PositionId::new(),
            pair,
            quantity,
            entry_price,
            current_price: entry_price,
            opened_at: Utc::now(),
            close_at: None,
        }
    }

    /// Get unrealized P&L in quote currency.
    pub fn unrealized_pnl(&self) -> f64 {
        let price_change = self.current_price - self.entry_price;
        (self.quantity as f64) * price_change
    }

    /// Get unrealized P&L as percentage.
    pub fn unrealized_pnl_percent(&self) -> f64 {
        if self.entry_price == 0.0 {
            return 0.0;
        }
        ((self.current_price - self.entry_price) / self.entry_price) * 100.0
    }

    /// Get position age.
    pub fn age(&self) -> Duration {
        Utc::now() - self.opened_at
    }

    /// Get value of position at current price.
    pub fn current_value(&self) -> f64 {
        (self.quantity as f64) * self.current_price
    }

    /// Check if position has expired (if close_at is set).
    pub fn is_expired(&self) -> bool {
        if let Some(close_at) = self.close_at {
            Utc::now() > close_at
        } else {
            false
        }
    }
}

/// A completed trade record.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Trade {
    /// Unique trade ID.
    pub id: String,
    /// Position this trade relates to.
    pub position_id: PositionId,
    /// Token pair traded.
    pub pair: TokenPair,
    /// Trade action (buy/sell).
    pub action: TradeAction,
    /// Quantity traded.
    pub quantity: u64,
    /// Price at execution.
    pub execution_price: f64,
    /// Total fees paid.
    pub fees: f64,
    /// Timestamp of execution.
    pub timestamp: DateTime<Utc>,
    /// Transaction signature (on-chain).
    pub tx_signature: Option<String>,
}

/// Trade action type.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum TradeAction {
    /// Buy/open long.
    Buy,
    /// Sell/close long.
    Sell,
}

impl Trade {
    /// Create a new trade record.
    pub fn new(
        position_id: PositionId,
        pair: TokenPair,
        action: TradeAction,
        quantity: u64,
        execution_price: f64,
        fees: f64,
    ) -> Self {
        Trade {
            id: format!("{}", Uuid::new_v4()),
            position_id,
            pair,
            action,
            quantity,
            execution_price,
            fees,
            timestamp: Utc::now(),
            tx_signature: None,
        }
    }

    /// Get total value of trade (quantity × price).
    pub fn total_value(&self) -> f64 {
        (self.quantity as f64) * self.execution_price
    }

    /// Get fees as basis points.
    pub fn fees_bps(&self) -> f64 {
        (self.fees / self.total_value()) * 10000.0
    }
}

/// Market data event types.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum MarketEvent {
    /// Price update event.
    PriceUpdate {
        token_pair: TokenPair,
        price: f64,
        source: String,
        timestamp: DateTime<Utc>,
    },
    /// Orderbook update event.
    OrderbookUpdate { orderbook: OrderBook },
    /// Liquidity update event.
    LiquidityUpdate {
        pair: TokenPair,
        available_liquidity: u64,
        timestamp: DateTime<Utc>,
    },
}

/// Portfolio state snapshot.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Portfolio {
    /// All open positions.
    pub positions: Vec<Position>,
    /// Total value in quote currency.
    pub total_value: f64,
    /// Available cash to deploy.
    pub available_capital: u64,
    /// Snapshot timestamp.
    pub timestamp: DateTime<Utc>,
}

impl Portfolio {
    /// Create empty portfolio.
    pub fn empty() -> Self {
        Portfolio {
            positions: Vec::new(),
            total_value: 0.0,
            available_capital: 0,
            timestamp: Utc::now(),
        }
    }

    /// Get total unrealized P&L.
    pub fn total_unrealized_pnl(&self) -> f64 {
        self.positions.iter().map(|p| p.unrealized_pnl()).sum()
    }

    /// Get portfolio concentration by pair.
    pub fn concentration(&self) -> HashMap<TokenPair, f64> {
        let mut concentration = HashMap::new();
        for position in &self.positions {
            let pct = position.current_value() / self.total_value;
            *concentration.entry(position.pair).or_insert(0.0) += pct;
        }
        concentration
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_position_id() {
        let id1 = PositionId::new();
        let id2 = PositionId::new();
        assert_ne!(id1, id2);
    }

    #[test]
    fn test_price_validation() {
        let pair = TokenPair::new(Pubkey::new_unique(), Pubkey::new_unique());
        let price = Price::new(100.0, pair, 0.95);
        assert!(price.is_valid());

        let invalid = Price::new(-50.0, pair, 0.5);
        assert!(!invalid.is_valid());
    }

    #[test]
    fn test_orderbook_spread() {
        let pair = TokenPair::new(Pubkey::new_unique(), Pubkey::new_unique());
        let book = OrderBook::new(pair, vec![(100.0, 1000)], vec![(101.0, 1000)]);

        assert_eq!(book.spread(), Some(1.0));
        assert_eq!(book.mid_price(), Some(100.5));
    }

    #[test]
    fn test_position_pnl() {
        let pair = TokenPair::new(Pubkey::new_unique(), Pubkey::new_unique());
        let mut position = Position::new(pair, 100, 100.0);
        position.current_price = 110.0;

        assert_eq!(position.unrealized_pnl(), 1000.0);
        assert_eq!(position.unrealized_pnl_percent(), 10.0);
    }

    #[test]
    fn test_signal_confidence_bounds() {
        let pair = TokenPair::new(Pubkey::new_unique(), Pubkey::new_unique());
        let signal = Signal::new(
            "test".to_string(),
            SignalType::Buy { pair },
            1.5, // Out of bounds
        );

        assert_eq!(signal.confidence, 1.0);
    }

    #[test]
    fn test_trade_fees_bps() {
        let pair = TokenPair::new(Pubkey::new_unique(), Pubkey::new_unique());
        let trade = Trade::new(
            PositionId::new(),
            pair,
            TradeAction::Buy,
            1000,
            100.0,
            0.25, // $0.25 fees on $100k
        );

        // Fees: 0.25 / 100000 * 10000 = 0.025 basis points
        assert!((trade.fees_bps() - 0.025).abs() < 0.001);
    }

    #[test]
    fn test_serialization() {
        let pair = TokenPair::new(Pubkey::new_unique(), Pubkey::new_unique());
        let position = Position::new(pair, 100, 100.0);

        let json = serde_json::to_string(&position).unwrap();
        let deserialized: Position = serde_json::from_str(&json).unwrap();

        assert_eq!(position.id, deserialized.id);
        assert_eq!(position.quantity, deserialized.quantity);
    }
}
