import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { BuiltInStrategyId } from "@trading-bot/shared";
import { config } from "../config.js";
import { strategyMetadata } from "../strategy-engine/registry.js";
import { TICK_COUNT_PARAMS, type SweepResult } from "./sweep.js";

const REPORTS_DIR = join(process.cwd(), "reports");

function fmtPct(n: number | null): string {
  return n === null ? "n/a" : `${n.toFixed(2)}%`;
}

function fmtRate(n: number | null): string {
  return n === null ? "n/a" : `${(n * 100).toFixed(1)}%`;
}

/** Tick-count params (see sweep.ts's TICK_COUNT_PARAMS) mean a different amount of real
 * time depending on candle spacing. Converts a backtest-tuned value into the equivalent
 * tick count at the live engine's actual poll interval, so it can be copied into a live
 * strategy config without silently changing what it means. */
function liveEquivalentNote(strategyId: BuiltInStrategyId, paramKey: string, tunedValue: number, candleIntervalSeconds: number): string {
  const tickCountParams = TICK_COUNT_PARAMS[strategyId] ?? [];
  if (!tickCountParams.includes(paramKey)) return "";
  const livePollSeconds = config.pricePollIntervalMs / 1000;
  const liveTicks = Math.round((tunedValue * candleIntervalSeconds) / livePollSeconds);
  return ` [tick-count param: ≈${liveTicks} ticks at the live ${config.pricePollIntervalMs}ms poll, not ${tunedValue} — see docs/ARCHITECTURE.md]`;
}

export function formatSweepConsole(result: SweepResult, candleIntervalSeconds: number): string {
  const meta = strategyMetadata[result.strategyId];
  const lines: string[] = [];
  lines.push(`\n=== ${meta.name} (${result.strategyId}) ===`);

  const b = result.baseline;
  lines.push(
    `Shipped defaults — tuning: return ${fmtPct(b.tuning.totalReturnPct)}, trades ${b.tuning.roundTripCount}, winRate ${fmtRate(b.tuning.winRate)}, maxDD ${fmtPct(b.tuning.maxDrawdownPct)}, fees ${fmtPct(b.tuning.feeDragPct)}`,
  );
  if (b.validation) {
    lines.push(`  validation: return ${fmtPct(b.validation.totalReturnPct)}, trades ${b.validation.roundTripCount}, maxDD ${fmtPct(b.validation.maxDrawdownPct)}`);
  }

  if (!result.best) {
    lines.push("No candidate cleared the minimum trade count on this data — not enough signal to tune yet.");
    return lines.join("\n");
  }

  const best = result.best;
  lines.push(
    `Tuned — tuning: return ${fmtPct(best.tuning.totalReturnPct)}, trades ${best.tuning.roundTripCount}, winRate ${fmtRate(best.tuning.winRate)}, maxDD ${fmtPct(best.tuning.maxDrawdownPct)}, fees ${fmtPct(best.tuning.feeDragPct)}`,
  );
  if (best.validation) {
    lines.push(`  validation: return ${fmtPct(best.validation.totalReturnPct)}, trades ${best.validation.roundTripCount}, maxDD ${fmtPct(best.validation.maxDrawdownPct)}`);
  }
  lines.push("Params:");
  for (const [key, value] of Object.entries(best.params)) {
    const defaultVal = meta.defaultParams[key];
    const changed = defaultVal !== value ? ` (was ${defaultVal})` : "";
    lines.push(`  ${key}: ${value}${changed}${liveEquivalentNote(result.strategyId, key, value, candleIntervalSeconds)}`);
  }
  return lines.join("\n");
}

export function writeCombinedReport(results: SweepResult[], candleIntervalSeconds: Partial<Record<BuiltInStrategyId, number>>): string {
  mkdirSync(REPORTS_DIR, { recursive: true });
  const date = new Date().toISOString().slice(0, 10);
  const path = join(REPORTS_DIR, `backtest-${date}.md`);

  const lines: string[] = [];
  lines.push(`# Backtest tuning report — ${date}`);
  lines.push("");
  lines.push(
    "Generated by `npm run backtest -- --strategy all`. \"Tuning\" is the first ~70% of fetched " +
      "history (chronological), \"validation\" is the held-out final ~30%, never used during the " +
      "search itself — see docs/ARCHITECTURE.md \"Backtesting\" for full methodology, the " +
      "tick-count-vs-live-cadence caveat, and known Phase-1 limitations of this backtest.",
  );
  lines.push("");

  for (const result of results) {
    const meta = strategyMetadata[result.strategyId];
    const intervalSeconds = candleIntervalSeconds[result.strategyId] ?? 60;
    lines.push(`## ${meta.name} (\`${result.strategyId}\`)`);
    lines.push("");
    lines.push("| | Tuning return | Tuning trades | Tuning winRate | Tuning maxDD | Validation return | Validation trades | Validation maxDD |");
    lines.push("|---|---|---|---|---|---|---|---|");
    const b = result.baseline;
    lines.push(
      `| Shipped defaults | ${fmtPct(b.tuning.totalReturnPct)} | ${b.tuning.roundTripCount} | ${fmtRate(b.tuning.winRate)} | ${fmtPct(b.tuning.maxDrawdownPct)} | ${b.validation ? fmtPct(b.validation.totalReturnPct) : "n/a"} | ${b.validation?.roundTripCount ?? "n/a"} | ${b.validation ? fmtPct(b.validation.maxDrawdownPct) : "n/a"} |`,
    );

    if (result.best) {
      const best = result.best;
      lines.push(
        `| Tuned | ${fmtPct(best.tuning.totalReturnPct)} | ${best.tuning.roundTripCount} | ${fmtRate(best.tuning.winRate)} | ${fmtPct(best.tuning.maxDrawdownPct)} | ${best.validation ? fmtPct(best.validation.totalReturnPct) : "n/a"} | ${best.validation?.roundTripCount ?? "n/a"} | ${best.validation ? fmtPct(best.validation.maxDrawdownPct) : "n/a"} |`,
      );
      lines.push("");
      lines.push("Tuned params:");
      for (const [key, value] of Object.entries(best.params)) {
        const defaultVal = meta.defaultParams[key];
        const note = defaultVal !== value ? ` _(default: ${defaultVal})_` : "";
        lines.push(`- \`${key}\`: ${value}${note}${liveEquivalentNote(result.strategyId, key, value, intervalSeconds)}`);
      }
    } else {
      lines.push("| Tuned | _no candidate cleared the minimum trade count_ | | | | | | |");
    }
    lines.push("");
  }

  writeFileSync(path, lines.join("\n"));
  return path;
}
