import type { BuiltInStrategyId, StrategyMetadata } from "@trading-bot/shared";
import type { StrategyBase } from "./StrategyBase.js";
import { DcaStrategy } from "./strategies/dca.js";
import { MomentumStrategy } from "./strategies/momentum.js";
import { MeanReversionStrategy } from "./strategies/meanReversion.js";
import { GridStrategy } from "./strategies/grid.js";
import { RsiMacdStrategy } from "./strategies/rsiMacd.js";
import { VolatilityBreakoutStrategy } from "./strategies/volatilityBreakout.js";
import { WhaleCopyStrategy } from "./strategies/whaleCopy.js";
import { ShortWindowGridStrategy } from "./strategies/shortWindowGrid.js";
import { RangeScalperStrategy } from "./strategies/rangeScalper.js";
import { ConfluenceScalperStrategy } from "./strategies/confluenceScalper.js";
import { FeeAwareScalperStrategy } from "./strategies/feeAwareScalper.js";
import { DipReversionStrategy } from "./strategies/dipReversion.js";
import { FlashDipReversalStrategy } from "./strategies/flashDipReversal.js";
import { DoubleBottomRetestStrategy } from "./strategies/doubleBottomRetest.js";

export const strategyMetadata: Record<BuiltInStrategyId, StrategyMetadata> = {
  dca: {
    id: "dca",
    name: "Dollar-Cost Averaging",
    description: "Buys a fixed USD amount of the target token at a fixed time interval, smoothing out entry price over time.",
    riskLevel: "low",
    backtestVerdict: "not-profitable",
    defaultParams: { intervalMinutes: 60, amountUsd: 100, takeProfitPct: 20 },
    paramDescriptions: {
      intervalMinutes: "Minutes between scheduled buys",
      amountUsd: "USD amount to buy each interval",
      takeProfitPct: "Optional: sell entire position once average entry gains this %  (0 to disable)",
    },
  },
  momentum: {
    id: "momentum",
    name: "Momentum / Trend-Following",
    description: "Buys when price breaks above its N-period high by a configurable margin. Volume confirmation is not yet available (Phase 1 limitation, see docs).",
    riskLevel: "high",
    backtestVerdict: "not-profitable",
    defaultParams: { lookbackPeriods: 20, breakoutPct: 1, positionSizeUsd: 200, takeProfitPct: 15 },
    paramDescriptions: {
      lookbackPeriods: "Number of price ticks to look back for the period high",
      breakoutPct: "% above the period high price must exceed to trigger a buy",
      positionSizeUsd: "USD size of each breakout buy",
      takeProfitPct: "Sell entire position once average entry gains this %",
    },
  },
  "mean-reversion": {
    id: "mean-reversion",
    name: "Mean Reversion (Std-Dev Bands)",
    description:
      "Buys when price falls a configurable number of standard deviations below its own rolling mean over a configurable real-time window (a Bollinger-Band-style entry, anchored to elapsed time rather than a tick count), and sells once price reverts back to that mean. Rebuilt from an earlier tick-count/flat-%-threshold version that had no confirmation tick, hard stop, time stop, or re-entry cooldown — see the class doc in strategy-engine/strategies/meanReversion.ts. Real backtest (14 days, 1m SOL/USD candles) plus a 150-trial tuning/validation sweep both came back net-negative: the shipped defaults lose -0.35%/-0.11% (tuning/validation) at a high 148/58-trade frequency, and the best config the sweep could find (wider 96min window, looser 3.36 std-dev entry, far fewer trades) only shrank the loss to -0.03%/-0.005% — still negative on both windows. Mean reversion on this token/timeframe reverts too shallowly, too often, to clear round-trip fees; no parameter set in the searched range flips it profitable.",
    riskLevel: "medium",
    backtestVerdict: "not-profitable",
    defaultParams: {
      windowMinutes: 60,
      entryStdDevs: 2,
      hardStopPct: 5,
      maxHoldMinutes: 120,
      reentryCooldownMinutes: 30,
      positionSizeUsd: 150,
    },
    paramDescriptions: {
      windowMinutes: "Rolling window (minutes, clamped 5-180) used to compute the mean and standard deviation",
      entryStdDevs: "Number of standard deviations below the window mean price must fall (and then turn up) to trigger a buy",
      hardStopPct: "Emergency backstop: fixed % below entry, always checked even before window data is available",
      maxHoldMinutes: "Time stop: exit any position held longer than this many minutes",
      reentryCooldownMinutes: "Minimum minutes since this config's last trade before a new entry is considered",
      positionSizeUsd: "USD size of each buy",
    },
  },
  grid: {
    id: "grid",
    name: "Grid Trading",
    description: "Buys and sells as price crosses fixed intervals within a price range. Approximates a real grid with one position at a time (Phase 1 limitation, see docs). Sits out if the range is too thin to be worth trading fees.",
    riskLevel: "medium",
    backtestVerdict: "not-profitable",
    defaultParams: { lowerPrice: 0, upperPrice: 0, gridLevels: 10, orderSizeUsd: 100, minRangePct: 0.3 },
    paramDescriptions: {
      lowerPrice: "Bottom of the grid price range (USD)",
      upperPrice: "Top of the grid price range (USD)",
      gridLevels: "Number of equal-sized steps between lowerPrice and upperPrice",
      orderSizeUsd: "USD size of each buy",
      minRangePct: "Skip trading entirely if the range is under this % of price (too thin to be worth fees)",
    },
  },
  "rsi-macd": {
    id: "rsi-macd",
    name: "RSI/MACD Crossover",
    description:
      "Enters on a bullish MACD crossover confirmed by RSI not being overbought; exits on a bearish crossover or RSI reaching overbought. overboughtRsi/positionSizeUsd retuned against ~180 days of real SOL/USD history (Birdeye) — see docs/ARCHITECTURE.md \"Backtesting\": exiting a bit earlier (66 vs 70) and sizing down (110 vs 200) held up on a held-out validation window where the shipped defaults didn't. rsiPeriod/macdFast/macdSlow/macdSignal are unchanged — see the same section for why a backtest-tuned period can't be safely applied here.",
    riskLevel: "medium",
    backtestVerdict: "not-profitable",
    defaultParams: { rsiPeriod: 14, macdFast: 12, macdSlow: 26, macdSignal: 9, overboughtRsi: 66, positionSizeUsd: 110 },
    paramDescriptions: {
      rsiPeriod: "Number of price ticks for the RSI calculation",
      macdFast: "MACD fast EMA period",
      macdSlow: "MACD slow EMA period",
      macdSignal: "MACD signal-line EMA period",
      overboughtRsi: "RSI level considered overbought (exit trigger)",
      positionSizeUsd: "USD size of each buy",
    },
  },
  "volatility-breakout": {
    id: "volatility-breakout",
    name: "Volatility Breakout",
    description: "Enters when a single price move exceeds a multiple of recent average volatility. Uses a close-to-close volatility proxy instead of true ATR (Phase 1 limitation, see docs).",
    riskLevel: "high",
    backtestVerdict: "not-profitable",
    defaultParams: { atrPeriod: 14, atrMultiplier: 2, positionSizeUsd: 200, takeProfitPct: 10 },
    paramDescriptions: {
      atrPeriod: "Number of price ticks for the volatility average",
      atrMultiplier: "Multiple of average volatility a single move must exceed to trigger a buy",
      positionSizeUsd: "USD size of each buy",
      takeProfitPct: "Sell entire position once average entry gains this %",
    },
  },
  "whale-copy": {
    id: "whale-copy",
    name: "Whale/Wallet Copy-Trading",
    description: "Mirrors trades detected on a watched on-chain wallet, scaled down and delayed. Read-only monitoring — never signs anything on the watched wallet's behalf. Requires a mainnet RPC (see docs) and a watched wallet address when configuring.",
    riskLevel: "high",
    backtestVerdict: "untested",
    defaultParams: { lagSeconds: 30, copyRatioPct: 10, maxSizeUsd: 200 },
    paramDescriptions: {
      lagSeconds: "Minimum age (seconds) a whale trade must reach before it's mirrored",
      copyRatioPct: "% of the whale's trade size to mirror",
      maxSizeUsd: "Hard cap on the USD size of each mirrored trade",
    },
  },
  "short-window-grid": {
    id: "short-window-grid",
    name: "Short-Window Grid (5-Min Auto-Range)",
    description: "A grid that auto-computes its price range every tick from the actual high/low of the last windowMinutes of movement, instead of a fixed manual range. Sits out entirely when that range is too thin to be worth trading fees, rather than churning on noise.",
    riskLevel: "medium",
    backtestVerdict: "not-profitable",
    defaultParams: { windowMinutes: 5, gridLevels: 6, orderSizeUsd: 100, minRangePct: 0.3 },
    paramDescriptions: {
      windowMinutes: "Rolling window (minutes) used to compute the grid's price range",
      gridLevels: "Number of equal-sized steps within that range",
      orderSizeUsd: "USD size of each buy",
      minRangePct: "Skip trading entirely if the auto-computed range is under this % of price (too thin to be worth fees)",
    },
  },
  "range-scalper": {
    id: "range-scalper",
    name: "Adaptive Range Scalper (1-15 Min)",
    description: "Scalps a rolling 1-15 minute price range with layered edge filters: a trend-regime filter (never buys 'support' in a falling market), a minimum-range filter (skips ranges too thin to cover costs), confirmation-tick entries (buys the turn, not the fall), a 1.2x reward:risk gate where both reward and risk scale with the observed range (not a fixed % of price, which made an earlier version nearly unfireable), a range-relative stop plus a fixed emergency backstop, a time stop, and a re-entry cooldown. No strategy guarantees profit; this one removes the classic ways scalpers lose.",
    riskLevel: "high",
    backtestVerdict: "not-profitable",
    defaultParams: {
      windowMinutes: 5,
      positionSizeUsd: 100,
      buyZonePct: 20,
      targetRangePct: 70,
      stopBufferPct: 10,
      hardStopPct: 2,
      minRangePct: 0.3,
      maxTrendEfficiency: 0.35,
      maxHoldMinutes: 10,
    },
    paramDescriptions: {
      windowMinutes: "Rolling analysis window in minutes (clamped to 1-15)",
      positionSizeUsd: "USD size of each buy",
      buyZonePct: "Entry zone: buy only when price is within this % of the range above the window low",
      targetRangePct: "Profit target as % of range height above the window low (never sells below entry on this trigger)",
      stopBufferPct: "Primary stop: % of the range below the window low (scales with observed volatility, not a fixed price %)",
      hardStopPct: "Emergency backstop: fixed % below entry, always checked even before window data is available",
      minRangePct: "Skip windows whose total range is under this % of price (too thin to cover costs)",
      maxTrendEfficiency: "Regime filter 0-1: skip entries when |net move| / path length exceeds this (market is trending, not ranging)",
      maxHoldMinutes: "Time stop: exit any position held longer than this many minutes",
    },
  },
  "confluence-scalper": {
    id: "confluence-scalper",
    name: "Confluence Scalper",
    description: "Combines the standard scalping TA toolkit into one entry: an EMA fast/slow trend filter, a Bollinger Band or RSI pullback signal, and a confirmation tick, so no single indicator alone can trigger a trade. Fixed % take-profit/stop-loss plus an exit if the trend itself flips.",
    riskLevel: "high",
    backtestVerdict: "not-profitable",
    defaultParams: {
      emaFastPeriod: 9,
      emaSlowPeriod: 21,
      bollingerPeriod: 20,
      bollingerStdDev: 2,
      rsiPeriod: 9,
      oversoldRsi: 45,
      overboughtRsi: 70,
      takeProfitPct: 0.3,
      stopLossPct: 0.15,
      maxHoldMinutes: 8,
      positionSizeUsd: 100,
    },
    paramDescriptions: {
      emaFastPeriod: "Fast EMA period (ticks) for the trend filter",
      emaSlowPeriod: "Slow EMA period (ticks) for the trend filter — only buys pullbacks while fast > slow",
      bollingerPeriod: "Bollinger Band lookback period (ticks)",
      bollingerStdDev: "Bollinger Band width in standard deviations",
      rsiPeriod: "RSI lookback period (ticks)",
      oversoldRsi: "RSI level (or lower Bollinger touch) that flags a pullback worth watching",
      overboughtRsi: "RSI level considered already overextended — blocks new entries",
      takeProfitPct: "Sell entire position once average entry gains this %",
      stopLossPct: "Sell entire position once average entry loses this %",
      maxHoldMinutes: "Time stop: exit any position held longer than this many minutes",
      positionSizeUsd: "USD size of each buy",
    },
  },
  "fee-aware-scalper": {
    id: "fee-aware-scalper",
    name: "Fee-Aware Micro Scalper",
    description: "Built for small accounts and high trade frequency, where trading costs (not price risk) are the real threat. The profit target and stop are computed directly from an estimated real Solana/Jupiter round-trip cost (the same one the simulator now charges on every fill) plus a safety margin — not an arbitrary %. Refuses to trade a dip unless the realistic bounce clearly covers costs.",
    riskLevel: "medium",
    backtestVerdict: "not-profitable",
    defaultParams: {
      positionSizeUsd: 20,
      smaPeriod: 12,
      dipPct: 0.08,
      minProfitMultiple: 1.5,
      stopLossMultiple: 1.0,
      maxHoldMinutes: 3,
    },
    paramDescriptions: {
      positionSizeUsd: "USD size of each buy — larger sizes dilute the fixed per-tx fee component",
      smaPeriod: "Short-term moving-average period (ticks) used as the 'fair value' anchor",
      dipPct: "Cheap pre-filter: minimum % below the SMA to even consider — the fee-derived requirement is usually the real (higher) gate, see docs",
      minProfitMultiple: "Required profit must be at least this multiple of the estimated round-trip fee",
      stopLossMultiple: "Stop-loss is set this multiple of the estimated round-trip fee below entry",
      maxHoldMinutes: "Time stop: exit any position held longer than this many minutes",
    },
  },
  "dip-reversion": {
    id: "dip-reversion",
    name: "Dip Reversion",
    description:
      "Buys a confirmed dip on a 30-180 minute timeframe and holds for a bounce. Was briefly this codebase's only \"profitable\"-verdict strategy after a 45-day backtest (+0.06% tuning / +0.01% validation) — but that entire 45-day window turned out to be a rising market (+15%). A 90-day two-regime retest, whose out-of-sample first half was a -23% decline, failed the shipped defaults: -0.13% on the decline-dominated tuning window (39 round trips, 41% win rate). The raw entry signal itself stays positive in both regimes; what fails in a decline is the exit package — the bounce target rarely fills before the hard/time stop does, and fees eat the rest. Verdict downgraded to not-profitable: the earlier result was a regime artifact. See the round-3 HONEST OUTCOME note in strategy-engine/strategies/dipReversion.ts for the full numbers, including why the retest sweep's positive-both-windows config (8 tuning / 2 validation trades) was rejected as overfit.",
    riskLevel: "medium",
    backtestVerdict: "not-profitable",
    defaultParams: {
      lookbackMinutes: 180,
      dipThresholdPct: 2.5,
      targetBouncePct: 1.5,
      holdMinutes: 180,
      hardStopPct: 5,
      reentryCooldownMinutes: 90,
      positionSizeUsd: 150,
    },
    paramDescriptions: {
      lookbackMinutes: "Rolling window (minutes, clamped 30-180) used to measure the dip from its recent high",
      dipThresholdPct: "Minimum decline from the window's high required to consider a buy",
      targetBouncePct: "Take-profit: sell once price bounces this % above entry",
      holdMinutes: "Time stop: exit any position held longer than this many minutes",
      hardStopPct: "Emergency backstop: fixed % below entry, always checked even before window data is available",
      reentryCooldownMinutes: "Minimum minutes since this config's last trade before a new entry is considered",
      positionSizeUsd: "USD size of each buy",
    },
  },
  "flash-dip-reversal": {
    id: "flash-dip-reversal",
    name: "Flash-Dip Reversal",
    description:
      "Buys a SHARP, concentrated price drop (most of the decline happening in the final third of a short 10-45min lookback) on a confirming uptick, and holds for a bounce — distinct from dip-reversion, which buys any dip of a given magnitude regardless of how fast it happened. Motivated by dip-reversion's own finding that its short-timeframe (10-20min) edge was real but too thin to beat fees; splitting that same signal by decline speed found fast flash-crash dips reverting more reliably than slow grinding declines on a raw, fee-free forward-return test. That raw edge did NOT survive contact with the real fee/execution/risk-manager backtest: a 45-day tuning/validation sweep found the shipped defaults net-negative on both windows (tuning -0.07%/33 trades, validation -0.01%/3 trades), and even the best tuned config the sweep could find — which looked good on the tuning window (+0.20%, 71.4% win rate) — still lost money on the 1-trade held-out validation window, the same overfitting signature that got an equally good-looking dip-reversion variant rejected. See the class doc in strategy-engine/strategies/flashDipReversal.ts for the raw-signal statistics that motivated the design, and docs/ARCHITECTURE.md \"Backtesting\" for why a real signal can still fail to clear the fee floor.",
    riskLevel: "medium",
    backtestVerdict: "not-profitable",
    defaultParams: {
      lookbackMinutes: 20,
      dropThresholdPct: 1,
      concentrationFraction: 0.6,
      targetBouncePct: 1,
      holdMinutes: 45,
      hardStopPct: 2.5,
      reentryCooldownMinutes: 20,
      positionSizeUsd: 150,
    },
    paramDescriptions: {
      lookbackMinutes: "Rolling window (minutes, clamped 10-45) used to measure the dip from its recent high",
      dropThresholdPct: "Minimum decline from the window's high required to consider a buy",
      concentrationFraction: "Minimum fraction of the total dip that must have happened within the final third of the lookback window — filters out slow grinding declines, keeps fast flash-crash-style drops",
      targetBouncePct: "Take-profit: sell once price bounces this % above entry",
      holdMinutes: "Time stop: exit any position held longer than this many minutes",
      hardStopPct: "Emergency backstop: fixed % below entry, always checked even before window data is available",
      reentryCooldownMinutes: "Minimum minutes since this config's last trade before a new entry is considered",
      positionSizeUsd: "USD size of each buy",
    },
  },
  "double-bottom-retest": {
    id: "double-bottom-retest",
    name: "Double-Bottom Retest",
    description:
      "Buys when price makes a low, bounces a real amount (>=1%) off it, pulls back to RETEST that same low without breaking meaningfully below it, then turns up again — a classic double-bottom shape. Stricter than dip-reversion/flash-dip-reversal's single-confirming-tick entry: requiring the low to be defended on a second visit filters out dead-cat bounces that look identical to a real reversal on the first tick alone. On independent, non-overlapping samples across 45 days of 1-minute data (fee-free, before any code was written), this was the strongest raw signal found in this codebase to date: n=78, 65.4% hit rate, +0.378% avg forward return, well above the ~0.3% round-trip fee floor. It did NOT hold up under the real fee/execution/risk-manager backtest: shipped defaults are barely positive on tuning (+0.03%, 59 trades, 52.5% win rate) but negative on the 11-trade held-out validation window (-0.06%); a 150-trial tuning sweep found a config that looked much better on tuning (+0.17%, 80% win rate) but only produced 1 validation trade — the same overfitting signature this codebase already rejected for flash-dip-reversal and an equally strong-looking dip-reversion variant. See the class doc in strategy-engine/strategies/doubleBottomRetest.ts for the full numbers and why a genuinely strong raw signal still didn't clear the bar.",
    riskLevel: "medium",
    backtestVerdict: "not-profitable",
    defaultParams: {
      lookbackMinutes: 90,
      bouncePct: 1,
      retestTolerancePct: 0.3,
      targetBouncePct: 1,
      holdMinutes: 60,
      hardStopPct: 2.5,
      reentryCooldownMinutes: 60,
      positionSizeUsd: 150,
    },
    paramDescriptions: {
      lookbackMinutes: "Rolling window (minutes, clamped 45-150) searched for the first-low / bounce / retest shape",
      bouncePct: "Minimum % bounce off the first low required before a pullback counts as a genuine retest setup",
      retestTolerancePct: "How close (%) the retest must come back to the first low to count as a valid retest",
      targetBouncePct: "Take-profit: sell once price bounces this % above entry",
      holdMinutes: "Time stop: exit any position held longer than this many minutes",
      hardStopPct: "Emergency backstop: fixed % below entry, always checked even before window data is available",
      reentryCooldownMinutes: "Minimum minutes since this config's last trade before a new entry is considered",
      positionSizeUsd: "USD size of each buy",
    },
  },
};

export const strategyRegistry: Record<BuiltInStrategyId, StrategyBase> = {
  dca: new DcaStrategy(),
  momentum: new MomentumStrategy(),
  "mean-reversion": new MeanReversionStrategy(),
  grid: new GridStrategy(),
  "rsi-macd": new RsiMacdStrategy(),
  "volatility-breakout": new VolatilityBreakoutStrategy(),
  "whale-copy": new WhaleCopyStrategy(),
  "short-window-grid": new ShortWindowGridStrategy(),
  "range-scalper": new RangeScalperStrategy(),
  "confluence-scalper": new ConfluenceScalperStrategy(),
  "fee-aware-scalper": new FeeAwareScalperStrategy(),
  "dip-reversion": new DipReversionStrategy(),
  "flash-dip-reversal": new FlashDipReversalStrategy(),
  "double-bottom-retest": new DoubleBottomRetestStrategy(),
};
